# Generated by Django 4.2.18 on 2025-01-29 00:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('answer_text', models.CharField(help_text='Введите текст ответа', max_length=300, verbose_name='Текст ответа')),
                ('is_correct', models.BooleanField(default=False, help_text='Выберите, является ли этот ответ правильным', verbose_name='Корректность ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='teachers.question')),
            ],
        ),
    ]
