# Generated by Django 4.2.18 on 2025-01-29 01:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0007_alter_answer_id_studentanswer'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('correct_answers', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teachers.student')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='teachers.test')),
            ],
        ),
    ]
