# Generated by Django 4.2.18 on 2025-01-29 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0008_studentresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='studentresult',
            options={'verbose_name': 'Результат студента', 'verbose_name_plural': 'Результаты студентов'},
        ),
    ]
