# Generated by Django 4.2.18 on 2025-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0009_alter_studentresult_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='nickname',
            field=models.CharField(default='default_nickname', help_text='Введите уникальный никнейм', max_length=50, unique=True, verbose_name='Никнейм'),
            preserve_default=False,
        ),
    ]
